---
- name: create vm inventory report
  hosts: localhost
  vars:
    resource_group: 'openenv-9kk9c'
  tasks:
  
  - name: get vm facts from azure
    azure_rm_virtualmachine_info:
      resource_group: "{{ resource_group }}"
    register: azure_vm_facts

  - debug:
      var: azure_vm_facts
