---
- name: gather linux vm facts
  hosts: linux
  gather_facts: true
  tasks:
  - name: print vm facts
    debug:
      var: ansible_facts
  - name: set vm facts
    set_fact: 
      vm_list: >
        "<tr>
         {% for host in groups['linux'] %}
           <td>{{hostvars[inventory_hostname].ansible_hostname}}</td>
           <td>{{ansible_facts.distribution}} {{ansible_facts.distribution_version}}</td>
           <td>{{ansible_facts['kernel']}}</td>
         {% endfor %}
         <tr>"
  - name: print vm_list
    debug:
      var: vm_list
