---
- name: gather linux vm facts
  hosts: linux
  gather_facts: true
  tasks:
  - name: set vm facts
    set_fact:
      vm_list: "{{hostvars[inventory_hostname].ansible_hostname}}"
  - name: print vm_list
    debug:
      var: vm_list
